export enum planetActionType {
    UPDATE_RADIUS = "UPDATE_RADIUS",
    UPDATE_SEED = "UPDATE_SEED",
    ADD_COLOR_MAPPING = "ADD_COLOR_MAPPING",
    UPDATE_COLOR_MAPPING = "UPDATE_COLOR_MAPPING",
    REMOVE_COLOR_MAPPING = "REMOVE_COLOR_MAPPING"
}